pipeline:
  name: content_shuffler
input:
  union:
    - pfs:
        glob: "/"
        repo: movie_gifer
    - pfs:
        glob: "/*.{png,jpg,jpeg}"
        repo: raw_videos_and_images
    - pfs:
        glob: "/*.{png,jpg,jpeg}"
        repo: image_tracer

transform:
  image: lbliii/content_shuffler:1.0.0
  cmd:
    - python3
    - /content_shuffler.py
    - --input
    - /pfs/movie_gifer
    - /pfs/raw_videos_and_images
    - /pfs/image_tracer
    - --output
    - /pfs/out/
autoscaling: true


# docker buildx build --platform linux/amd64 -t lbliii/content_shuffler:1.0.0 --push .

