pipeline:
  name: content_collager
input:
  pfs:
    glob: "/"
    repo: content_shuffler


transform:
  image: lbliii/content_collager:1.0.64
  cmd:
    - python3
    - /content_collager.py
    - --input
    - /pfs/content_shuffler
    - --output
    - /pfs/out/
autoscaling: true


# docker buildx build --platform linux/amd64 -t lbliii/content_collager:1.0.64 --push .

