pipeline:
  name: image_tracer
description: A pipeline that performs image edge detection by using the OpenCV library.
input:
  union:
    - pfs:
        repo: raw_videos_and_images
        name: tracer
        glob: "/*.{png,jpg,jpeg}"
    - pfs:
        repo: image_flattener
        name: tracer
        glob: "/*"
transform:
  image: lbliii/image_tracer:1.0.9
  cmd:
    - python3
    - /image_tracer.py
    - --input
    - /pfs/tracer
    - --output
    - /pfs/out/
autoscaling: true


# docker buildx build --platform linux/amd64 -t lbliii/image_tracer:1.0.9 --push .